# -*- coding: utf-8 -*-
"""cours_session1_data_handling(dirty_titanic).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eZGXiweYPCPuSN2WFEVgUHt0chex_0Dc

A) Load and Preview the Data
"""

#1# import package
import pandas as pd
import numpy as np

#2# import data
# Save the copied file path as a variable
# Surround the path with quotes
path= '/content/drive/MyDrive/TD_machine_learning/Session1/titanic_dirty.csv'

# Load in the file as a Pandas dataframe named df
df= pd.read_csv(path)

df

# Preview the first 5 rows with .head()
df.head(8)

# Preview the last 5 rows with .tail()
df.tail()

# Obtain summary information with .info()
df.info()

"""a) How many rows are there?

- Answer: 906

b) How many columns are there?

- Answer: 13
"""

df.dtypes

"""**B/ Cleaning Data**"""

df['Fare'].value_counts()

"""

```
```
We see values that contain string characters that need to be replaced ("$")

```
```

"""

# Replace the $ by nothing
df['Fare']= df['Fare'].str.replace('$','')

# Change the type of the column "Fare" from object(string) to float
df['Fare']= df['Fare'].astype(float)

df.info()

"""C) Drop Unwanted columns:"""

df= df.drop(columns= ['Unnamed: 0'])

df.head()

"""D) Rename Columns:"""

df['SibSp'].rename('Siblings or Spouses')

df.info()

df.head()

# Rename the column Sibsp (new name: Siblings or Spouses )
df.rename(columns={'SibSp':'Siblings or Spouses'})

"""E) Duplicate Rows"""

df.duplicated()

"""How many duplicate rows are in the data? ----- 5 rows"""

# Eliminate duplicated rows
df= df.drop_duplicates()

# Check
df.duplicated()

# the sum of duplicated rows
df.duplicated().sum()

"""F) Unique Identifiers"""

df.nunique()

""" F1) Which columns have 100% unique values?------ PassengerId and Name"""

# Changing the index
df.set_index('PassengerId', inplace=True)

# Dropping the Name column
df.drop(columns=['Name'], inplace=True)

"""G) Missing Values"""

# Verify if there are missing values
df.isna() # is there NAN values ? ___ output= bool: False means no NAN , True means yes there is NAN value

# or you can use .isnull(), both are similar
df.isnull()

df.isna().sum()

# Sum of nan values__ output= number
null_sums = df.isna().sum()

null_percent = null_sums/len(df) * 100
null_percent

# Visualize missing values in the dataset using a matrix plot
import missingno as msno
msno.matrix(df)

df.dtypes

#The .fillna() method replaces all NaN (missing values) in the Age column with the specified value, which in this case is -1
df['Age'].fillna(-1, inplace=True)

df.isna()

"""**H) Slicing Data**"""

# Find all the column Parch
df.Parch

# or
df[['Parch']] # double brackets __> output: data frame

# or with single bracket__> output: A pandas Series
df['Parch']

# Use single brackets so the output is a Pandas Series
#.loc[] : locate row number 50
df.loc[50]

# Use double brackets so the output is a Pandas Dataframe
df.loc[[50]]

# find out if the Passenger at index 20 was a male or female by slicing index 20 and column "Sex"
df.loc[20, 'Sex']

# To see how many Passenger are male
(df['Sex'] == "male").sum()